### ISSUE TITLE
The examples list don't fit on my screen.

### ISSUE THREAD

**Issue by Erkaman** [freeman-lab/regl#10]
The list of examples barely fit on my screen. on my MacBook it looks like this:

<img width="1272" alt="screen shot 2016-07-14 at 07 57 18" src="https://cloud.githubusercontent.com/assets/602313/16829459/a671fa32-4998-11e6-8288-bfe282827e21.png">

as can be seen, the "video" link barely fit on my screen. And if more examples are added below "video", I will not be able to click them at al. The list of examples need some kind of scrollbar, I think.

**Comment by freeman-lab** [comment]
ah yes, should def have a scrollbar, thanks! will add that

**Comment by freeman-lab** [comment]
fixed in https://github.com/freeman-lab/regl-site/commit/21d12aa31236a6ab678384d84da47b9a1bd0faf3
